server:
  port: 9002

spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos: # ali nacos 配置
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
