server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route # 路路由的id，没有固定规则但要求唯一，建议配合service name
          uri: http://localhost:8001 # 匹配路由后，提供服务的地址
          predicates:
            - Path=/payment/**  # 断言，路径匹配的进行路由

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # 指定eureka server地址
  instance:
    instance-id: gateway9527  # 配置服务的主机名
    prefer-ip-address: true # 显示服务ip地址


