server:
  port: 2001

spring:
  application:
    name: seata-order-service
  # 配置数据源
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  # mysql驱动包
    #driver-class-name: org.gjt.mm.mysql.Driver  # mysql驱动包
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  cloud:
    nacos: # ali nacos 配置
      discovery:
        server-addr: localhost:8848
        group: SEATA_GROUP

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # mapper文件路径
  type-aliases-package: com.rhythm.entities # 所有Entity别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server # 这里要和seata server端的值一致
      server-addr: localhost:8848
      cluster: default
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      data-id: seata.properties
      username: nacos
      password: nacos
      group: SEATA_GROUP
  enabled: true # 是否开启spring-boot自动装配，如果开启，则会自动配置seata与spring-boot的集成，包括数据源的自动代理以及GlobalTransactionScanner初始化。 注：1.0版本新特性，需依赖seata-spring-boot-starter。
  service:
    vgroup-mapping:
      my_test_tx_group: default
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true

feign:
  client:
    config:
      default: # default：设置所有服务
        connectTimeout: 5000
        readTimeout: 5000
